# Generated by Django 5.2.12 on 2026-03-20 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stops', '0002_stop_name'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIF_train_uid', models.CharField(max_length=64, unique=True)),
                ('schedule_days_runs', models.CharField(blank=True, max_length=16, null=True)),
                ('schedule_start_date', models.DateField(blank=True, null=True)),
                ('schedule_end_date', models.DateField(blank=True, null=True)),
                ('train_status', models.CharField(blank=True, max_length=8, null=True)),
                ('headcode', models.CharField(blank=True, max_length=16, null=True)),
                ('CIF_headcode', models.CharField(blank=True, max_length=16, null=True)),
                ('train_service_code', models.CharField(blank=True, max_length=32, null=True)),
                ('power_type', models.CharField(blank=True, max_length=32, null=True)),
                ('max_speed', models.IntegerField(blank=True, null=True)),
                ('train_class', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetables', to='main.operator')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(blank=True, max_length=8, null=True)),
                ('tiploc_code', models.CharField(blank=True, max_length=64, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=16, null=True)),
                ('arrival_time', models.CharField(blank=True, max_length=16, null=True)),
                ('pass_time', models.CharField(blank=True, max_length=16, null=True)),
                ('platform', models.CharField(blank=True, max_length=16, null=True)),
                ('engineering_allowance', models.CharField(blank=True, max_length=16, null=True)),
                ('pathing_allowance', models.CharField(blank=True, max_length=16, null=True)),
                ('performance_allowance', models.CharField(blank=True, max_length=16, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_locations', to='Stops.stop')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_locations', to='Depatures.timetable')),
            ],
        ),
    ]
