# Generated by Django 5.2.12 on 2026-03-20 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depatures', '0001_initial'),
        ('Stops', '0002_stop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='schedule_locations',
            field=models.ManyToManyField(related_name='timetables', through='Depatures.ScheduleLocation', to='Stops.stop'),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_entries', to='Depatures.timetable'),
        ),
    ]
