# Generated by Django 5.2.12 on 2026-03-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depatures', '0002_timetable_schedule_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulelocation',
            name='sort_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
