# Generated by Django 5.2.12 on 2026-03-26 09:03

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('Depatures', '0003_schedulelocation_sort_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulelocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulelocation',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulelocation',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedulelocation',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
