# Generated by Django 5.2.12 on 2026-03-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depatures', '0004_schedulelocation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='CIF_train_uid',
            field=models.CharField(max_length=64),
        ),
    ]
