# Generated by Django 5.2.12 on 2026-03-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depatures', '0005_alter_timetable_cif_train_uid'),
        ('Stops', '0006_stop_show_on_map'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schedulelocation',
            index=models.Index(fields=['tiploc_code'], name='Depatures_s_tiploc__a4be09_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulelocation',
            index=models.Index(fields=['stop'], name='Depatures_s_stop_id_a52748_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulelocation',
            index=models.Index(fields=['timetable'], name='Depatures_s_timetab_54ba96_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulelocation',
            index=models.Index(fields=['sort_time'], name='Depatures_s_sort_ti_7c6468_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulelocation',
            index=models.Index(fields=['from_date', 'to_date'], name='Depatures_s_from_da_264a55_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulelocation',
            index=models.Index(fields=['stop', 'sort_time'], name='Depatures_s_stop_id_1d5754_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulelocation',
            index=models.Index(fields=['timetable', 'position'], name='Depatures_s_timetab_768682_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['CIF_train_uid'], name='Depatures_t_CIF_tra_83629d_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['headcode'], name='Depatures_t_headcod_6a49a4_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['train_service_code'], name='Depatures_t_train_s_25ed31_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['schedule_start_date', 'schedule_end_date'], name='Depatures_t_schedul_deaa11_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['operator'], name='Depatures_t_operato_94e7d6_idx'),
        ),
    ]
