# Generated by Django 5.2.12 on 2026-03-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depatures', '0006_schedulelocation_depatures_s_tiploc__a4be09_idx_and_more'),
        ('Stops', '0006_stop_show_on_map'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='schedulelocation',
            name='Depatures_s_tiploc__a4be09_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulelocation',
            name='Depatures_s_stop_id_a52748_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulelocation',
            name='Depatures_s_timetab_54ba96_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulelocation',
            name='Depatures_s_sort_ti_7c6468_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulelocation',
            name='Depatures_s_from_da_264a55_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulelocation',
            name='Depatures_s_stop_id_1d5754_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulelocation',
            name='Depatures_s_timetab_768682_idx',
        ),
        migrations.RemoveIndex(
            model_name='timetable',
            name='Depatures_t_CIF_tra_83629d_idx',
        ),
        migrations.RemoveIndex(
            model_name='timetable',
            name='Depatures_t_headcod_6a49a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='timetable',
            name='Depatures_t_train_s_25ed31_idx',
        ),
        migrations.RemoveIndex(
            model_name='timetable',
            name='Depatures_t_schedul_deaa11_idx',
        ),
        migrations.RemoveIndex(
            model_name='timetable',
            name='Depatures_t_operato_94e7d6_idx',
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='arrival_time',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='departure_time',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='engineering_allowance',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='from_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='location_type',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='pass_time',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='pathing_allowance',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='performance_allowance',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='platform',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='sort_time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='tiploc_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='to_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='CIF_headcode',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='CIF_train_uid',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='headcode',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='max_speed',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='power_type',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='schedule_days_runs',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='schedule_end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='schedule_locations',
            field=models.ManyToManyField(db_index=True, related_name='timetables', through='Depatures.ScheduleLocation', to='Stops.stop'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='schedule_start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='train_class',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='train_service_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='train_status',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
    ]
