# Generated by Django 5.2.12 on 2026-03-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depatures', '0008_remove_timetable_schedule_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelocation',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
