# Generated by Django 5.2.12 on 2026-03-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depatures', '0009_alter_schedulelocation_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='CIF_train_category',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
