# Generated by Django 5.2.12 on 2026-03-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depatures', '0010_timetable_cif_train_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='CIF_timing_load',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
