# Generated by Django 5.2.12 on 2026-03-31 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depatures', '0012_pathtype_powertype_traincategory_trainclass_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimingLoadTOCCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('TOC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tocc_corrections', to='main.operator')),
                ('type', models.ManyToManyField(related_name='tocc_corrections', to='Depatures.pathtype')),
            ],
        ),
    ]
