# Generated by Django 5.2.12 on 2026-03-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depatures', '0013_timingloadtoccorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='timingload',
            name='TOC_correction',
            field=models.JSONField(blank=True, help_text='JSON object mapping TOC codes to correction types e.g. 323s on LM are 730 (e.g. {"LM": "730"})', null=True),
        ),
        migrations.DeleteModel(
            name='TimingLoadTOCCorrection',
        ),
    ]
