# Generated by Django 5.2.12 on 2026-04-10 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depatures', '0014_timingload_toc_correction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_type', models.CharField(blank=True, max_length=16, null=True)),
                ('from_location', models.CharField(blank=True, max_length=64, null=True)),
                ('to_location', models.CharField(blank=True, max_length=64, null=True)),
                ('headcode', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='Depatures.timetable')),
            ],
        ),
    ]
