# Generated by Django 5.2.12 on 2026-04-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depatures', '0015_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='run_by',
            field=models.CharField(blank=True, help_text='Operator code that runs this route, if different from timetable operator', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
