# Generated by Django 5.2.12 on 2026-04-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depatures', '0016_route_end_date_route_run_by_route_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelocation',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='pass_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
