# Generated by Django 5.2.12 on 2026-04-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depatures', '0017_alter_schedulelocation_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelocation',
            name='arrival_time',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='departure_time',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelocation',
            name='pass_time',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
