# Generated by Django 5.2.12 on 2026-04-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleetnumber', models.CharField(db_index=True, max_length=32, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('livery_name', models.CharField(blank=True, default='', max_length=255)),
                ('livery_css', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['fleetnumber'],
            },
        ),
    ]
