# Generated by Django 5.2.12 on 2026-04-07 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_trains'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trains', to='main.operator'),
        ),
    ]
