# Generated by assistant to add missing original_values column safely
from django.db import migrations, models


def forwards(apps, schema_editor):
    TrainEditRequest = apps.get_model('main', 'TrainEditRequest')
    conn = schema_editor.connection
    table = TrainEditRequest._meta.db_table
    cursor = conn.cursor()
    try:
        cols = []
        if conn.vendor == 'sqlite':
            cursor.execute(f"PRAGMA table_info('{table}')")
            cols = [row[1] for row in cursor.fetchall()]
        elif conn.vendor == 'mysql':
            cursor.execute(f"SHOW COLUMNS FROM {table}")
            cols = [row[0] for row in cursor.fetchall()]
        else:
            try:
                cursor.execute(f"PRAGMA table_info('{table}')")
                cols = [row[1] for row in cursor.fetchall()]
            except Exception:
                cols = []

        if 'original_values' not in cols:
            field = models.JSONField(blank=True, null=True)
            field.set_attributes_from_name('original_values')
            schema_editor.add_field(TrainEditRequest, field)
    finally:
        cursor.close()


def reverse(apps, schema_editor):
    TrainEditRequest = apps.get_model('main', 'TrainEditRequest')
    conn = schema_editor.connection
    table = TrainEditRequest._meta.db_table
    cursor = conn.cursor()
    try:
        cols = []
        if conn.vendor == 'sqlite':
            cursor.execute(f"PRAGMA table_info('{table}')")
            cols = [row[1] for row in cursor.fetchall()]
        elif conn.vendor == 'mysql':
            cursor.execute(f"SHOW COLUMNS FROM {table}")
            cols = [row[0] for row in cursor.fetchall()]
        else:
            try:
                cursor.execute(f"PRAGMA table_info('{table}')")
                cols = [row[1] for row in cursor.fetchall()]
            except Exception:
                cols = []

        if 'original_values' in cols:
            field = TrainEditRequest._meta.get_field('original_values')
            schema_editor.remove_field(TrainEditRequest, field)
    finally:
        cursor.close()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_rename_reviewer_column"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
