# Generated by Django 5.2.12 on 2026-04-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_original_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('inbound_destination', models.CharField(max_length=255)),
                ('outbound_destination', models.CharField(max_length=255)),
                ('full_description', models.TextField(blank=True, default='')),
                ('route_data', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
