# Generated by Django 5.2.12 on 2026-04-20 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_historicalroutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalroutes',
            name='full_description',
        ),
    ]
