# Generated by Django 5.2.12 on 2026-04-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_historicalroutes_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroutes',
            name='stops',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
