# Generated by Django 5.2.12 on 2026-04-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_historicalroutes_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroutes',
            name='operators',
            field=models.TextField(blank=True, default=''),
        ),
    ]
