# Generated by Django 5.2.12 on 2026-04-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_historicalroutes_operators'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainRID',
            fields=[
                ('rid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('headcode', models.CharField(blank=True, default='', max_length=16)),
                ('uid', models.CharField(blank=True, default='', max_length=16)),
                ('toc_code', models.CharField(blank=True, default='', max_length=8)),
                ('train_operator', models.CharField(blank=True, default='', max_length=128)),
                ('origin_crs', models.CharField(blank=True, default='', max_length=8)),
                ('origin_name', models.CharField(blank=True, default='', max_length=128)),
                ('origin_departure', models.DateTimeField(blank=True, null=True)),
                ('destination_crs', models.CharField(blank=True, default='', max_length=8)),
                ('destination_name', models.CharField(blank=True, default='', max_length=128)),
                ('destination_arrival', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Train RID',
                'verbose_name_plural': 'Train RIDs',
                'db_table': 'train_rid',
            },
        ),
    ]
