# Generated by Django 5.2.12 on 2026-04-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_trainrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainrid',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
