# Generated by Django 5.2.12 on 2026-03-19 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StopType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sub_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_types', to='Stops.stoptype')),
            ],
            options={
                'verbose_name': 'Stop Type',
                'verbose_name_plural': 'Stop Types',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atco_code', models.CharField(blank=True, max_length=64, null=True)),
                ('naptan_code', models.CharField(blank=True, max_length=64, null=True)),
                ('tiploc', models.CharField(blank=True, max_length=64, null=True)),
                ('crs', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('bearing', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('lines', models.CharField(blank=True, max_length=255, null=True)),
                ('indicator', models.CharField(blank=True, max_length=64, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stops', to='Stops.stoptype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
