# Generated by Django 5.2.12 on 2026-03-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
