# Generated by Django 5.2.12 on 2026-03-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stops', '0002_stop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='atco_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='bearing',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='crs',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='icon',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='indicator',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='lat',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='lines',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='lon',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='naptan_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='tiploc',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
