# Generated by Django 5.2.12 on 2026-03-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stops', '0003_alter_stop_active_alter_stop_atco_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='common_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='long_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
