# Generated by Django 5.2.12 on 2026-03-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stops', '0004_stop_common_name_stop_long_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='other_crs',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='other_tiplocs',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
