# Generated by Django 5.2.12 on 2026-03-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stops', '0005_stop_other_crs_stop_other_tiplocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='show_on_map',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
