"""
Django settings for TransportStatistics project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
load_dotenv()
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l+q+qn&@=w!g&xqhym7@@@1o=-e=r&*yrt&*vs0)znz30l)8(i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'main',
    'API',
    'Depatures',
    'Stops',
    'Trips',
    'Web',
]

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # increase default limit of 1000 for large JSON imports

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TransportStatistics.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TransportStatistics.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os
from urllib.parse import urlparse, parse_qs

# Default to a local sqlite database. This may be overridden by setting
# the environment variable `DATABASE_URL` to a URL such as:
#   sqlite:///db.sqlite3
#   sqlite:////absolute/path/to/db.sqlite3
#   sqlite:///:memory:
#   mysql://user:pass@host:port/dbname
#   postgres://user:pass@host:port/dbname
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
    )
}

# Allow configuring database with a single DATABASE_URL environment variable.
# Supports sqlite and mysql (postgresql also handled as a convenience).
db_url = os.getenv('DATABASE_URL')
if db_url:
    parsed = urlparse(db_url)
    scheme = (parsed.scheme or '').lower()

    if scheme.startswith('mysql'):
        ENGINE = 'django.db.backends.mysql'
    elif scheme.startswith('postgres') or scheme.startswith('postgresql'):
        ENGINE = 'django.db.backends.postgresql'
    elif scheme == 'sqlite':
        ENGINE = 'django.db.backends.sqlite3'
    else:
        ENGINE = 'django.db.backends.sqlite3'

    if ENGINE == 'django.db.backends.sqlite3':
        # Handle common sqlite URL forms. Treat three slashes as project-relative
        # (sqlite:///db.sqlite3) and four slashes as absolute file paths
        path = parsed.path or ''
        if path == '/:memory:' or path == ':memory:':
            NAME = ':memory:'
        else:
            # sqlite:///db.sqlite3 -> relative to BASE_DIR
            if db_url.startswith('sqlite:///') and not db_url.startswith('sqlite:////'):
                NAME = BASE_DIR / path.lstrip('/')
            else:
                NAME = Path(path)

        DATABASES['default'] = {
            'ENGINE': ENGINE,
            'NAME': str(NAME),
        }
    else:
        # network-backed DB (mysql/postgres)
        NAME = (parsed.path or '').lstrip('/')
        USER = parsed.username or ''
        PASSWORD = parsed.password or ''
        HOST = parsed.hostname or ''
        PORT = str(parsed.port) if parsed.port else ''

        # convert query params into OPTIONS where appropriate
        query = parse_qs(parsed.query)
        OPTIONS = {}
        # For example: ?charset=utf8mb4
        if 'charset' in query:
            OPTIONS['charset'] = query['charset'][-1]

        DATABASES['default'] = {
            'ENGINE': ENGINE,
            'NAME': NAME,
            'USER': USER,
            'PASSWORD': PASSWORD,
            'HOST': HOST,
            'PORT': PORT,
            'OPTIONS': OPTIONS,
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static', 
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication redirects
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
