# Generated by Django 5.2.12 on 2026-03-21 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('headcode', models.CharField(blank=True, max_length=20)),
                ('operator', models.CharField(blank=True, max_length=120)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('transport_type', models.CharField(blank=True, choices=[('rail', 'Rail'), ('bus', 'Bus'), ('tram', 'Tram'), ('ferry', 'Ferry')], default='rail', max_length=10)),
                ('origin_name', models.CharField(blank=True, max_length=200)),
                ('origin_crs', models.CharField(blank=True, max_length=10)),
                ('origin_tiploc', models.CharField(blank=True, max_length=20)),
                ('destination_name', models.CharField(blank=True, max_length=200)),
                ('destination_crs', models.CharField(blank=True, max_length=10)),
                ('destination_tiploc', models.CharField(blank=True, max_length=20)),
                ('scheduled_departure', models.TimeField(blank=True, null=True)),
                ('actual_departure', models.TimeField(blank=True, null=True)),
                ('boarded_stop_name', models.CharField(blank=True, max_length=200)),
                ('boarded_stop_crs', models.CharField(blank=True, max_length=10)),
                ('boarded_stop_atco', models.CharField(blank=True, max_length=30)),
                ('route_geometry', models.JSONField(blank=True, help_text='GeoJSON LineString coordinate array [[lon,lat],...]', null=True)),
                ('train_fleet_number', models.CharField(blank=True, max_length=20)),
                ('train_type', models.CharField(blank=True, help_text='e.g. Class 390, Pendolino', max_length=60)),
                ('bus_fleet_number', models.CharField(blank=True, max_length=20)),
                ('bus_registration', models.CharField(blank=True, help_text='e.g. BV24 LSJ', max_length=12)),
                ('bus_type', models.CharField(blank=True, help_text='e.g. Wrightbus StreetDeck', max_length=80)),
                ('bus_livery', models.CharField(blank=True, help_text='Hex colour code, e.g. #15803d', max_length=30)),
                ('bus_livery_name', models.CharField(blank=True, help_text='e.g. First Greater Manchester pink', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip log',
                'verbose_name_plural': 'Trip logs',
                'ordering': ['-logged_at'],
            },
        ),
    ]
