# Generated by Django 5.2.12 on 2026-03-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplog',
            name='bus_livery',
            field=models.TextField(blank=True, help_text='Hex colour code, e.g. #15803d'),
        ),
    ]
