# Generated by Django 5.2.12 on 2026-03-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0002_alter_triplog_bus_livery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triplog',
            old_name='actual_departure',
            new_name='scheduled_arrival',
        ),
        migrations.AddField(
            model_name='triplog',
            name='full_route_geometry',
            field=models.JSONField(blank=True, help_text='GeoJSON LineString coordinate array [[lon,lat],...] for the full route (not just the boarded stop onwards)', null=True),
        ),
    ]
