# Generated by Django 5.2.12 on 2026-03-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0003_rename_actual_departure_triplog_scheduled_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplog',
            name='full_locations',
            field=models.JSONField(blank=True, help_text='Array of all locations passed through, with timestamps and stop info, e.g. [{"name": "Stop A", "crs": "AAA", "tiploc": "AAA", "arrival": "15:04", "departure": "15:05"}, ...]', null=True),
        ),
    ]
