# Generated by Django 5.2.12 on 2026-03-29 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0005_importjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='triplog',
            name='on_trip_trip',
            field=models.ManyToManyField(blank=True, help_text='Other users who were on the same trip (e.g. friends you travelled with) - optional, for social features and trip grouping', related_name='on_trip_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
