# Generated by Django 5.2.12 on 2026-04-14 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0006_triplog_on_trip_trip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpottedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('headcode', models.CharField(blank=True, max_length=20)),
                ('logged_at_location', models.CharField(blank=True, max_length=200)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('operator', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('unit_number', models.CharField(blank=True, max_length=20)),
                ('reg', models.CharField(blank=True, max_length=12)),
                ('vehicle_type', models.CharField(blank=True, max_length=80)),
                ('livery', models.CharField(blank=True, max_length=80)),
                ('livery_name', models.CharField(blank=True, max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotted_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spotted log',
                'verbose_name_plural': 'Spotted logs',
                'ordering': ['-logged_at'],
            },
        ),
    ]
