# Generated by Django 5.2.12 on 2026-04-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0007_spottedlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spottedlog',
            name='service_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
