# Generated by Django 5.2.12 on 2026-04-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0008_alter_spottedlog_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spottedlog',
            name='logged_at_location',
            field=models.TextField(blank=True),
        ),
    ]
