# Generated by Django 5.2.12 on 2026-04-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0009_alter_spottedlog_logged_at_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplog',
            name='bustimes_service_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
