# Generated by Django 5.2.12 on 2026-04-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0010_triplog_bustimes_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplog',
            name='bustimes_service_slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
